name: Daily News (JST)

on:
  # 手动触发
  workflow_dispatch:

  # 定时触发（UTC 时间）。例：北京时间/日本时间 08:30 ≈ UTC 前一天 23:30
  schedule:
    - cron: '30 23 * * *'

  # 当这些文件有变更时自动构建并部署
  push:
    branches: [ main ]
    paths:
      - 'public/**'
      - 'fetch_news.py'
      - 'requirements.txt'
      - '.github/workflows/daily.yml'

# 防止同一分支上多次并发运行导致 artifact 冲突（409）
concurrency:
  group: pages-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

env:
  # 让脚本和页面默认按日本时区运作
  TZ: Asia/Tokyo
  PYTHONUNBUFFERED: '1'

jobs:
  build:
    name: Build site (generate data & bundle)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -V
          pip install -r requirements.txt

      - name: Generate news data (JST)
        run: |
          python fetch_news.py
        # 你的脚本会在 public/data/ 写入 YYYY-MM-DD.json/.md

      # ✅ 只在这里上传一次 Pages artifact，避免 409 Conflict
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public   # 必须包含 index.html、app.js、data/ 等

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
