name: Daily News (JST)

on:
  schedule:
    - cron: "30 23 * * *"   # 每天 23:30 UTC = 次日 08:30 JST
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Fetch news (JST)
        env:
          TZ: Asia/Tokyo
        run: |
          python fetch_news.py
          ls -la public/data
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/*.json public/data/*.md || true
          git commit -m "chore: daily news $(date -u '+%Y-%m-%dT%H:%MZ')" || echo "No changes"
          git push
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
